name: Build OpenWrt 18.06 for Orange Pi Zero H2+

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      OPENWRT_VERSION: v18.06.4
      FORCE_UNSAFE_CONFIGURE: 1
      CLEAN_OLD_PACKAGES: 1
      DEBIAN_FRONTEND: noninteractive
      TZ: UTC

    steps:
    - name: Show System Info
      run: |
        echo "Build started at: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "Running as user: ${{ github.actor }}"
        echo "Initial space available:"
        df -h

    - name: Free Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt-get clean
        echo "Space after cleanup:"
        df -h

    - name: Initialize Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
        python3-distutils python3-setuptools rsync subversion swig time \
        xsltproc zlib1g-dev 

    - name: Cache downloads
      uses: actions/cache@v4
      with:
        path: openwrt/dl
        key: ${{ runner.os }}-openwrt-dl-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-openwrt-dl-
        max-size: 5GB

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-
        max-size: 2GB

    - name: Setup ccache
      run: |
        mkdir -p ~/.ccache
        echo "max_size = 2G" > ~/.ccache/ccache.conf
        echo "hash_dir = false" >> ~/.ccache/ccache.conf
        echo "compression = true" >> ~/.ccache/ccache.conf
        echo "compression_level = 9" >> ~/.ccache/ccache.conf

    - name: Download OpenWrt
      run: |
        git clone -b v18.06.4 --depth 1 https://github.com/melsem/openwrt-18.06.4.git openwrt
        cd openwrt
        echo "Space after OpenWrt download:"
        df -h

    - name: Setup feeds and xr819 driver
      working-directory: openwrt
      run: |
        # Update feeds
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # Download xr819 firmware
        mkdir -p package/kernel/xradio
        wget -O package/kernel/xradio/Makefile https://raw.githubusercontent.com/melsem/openwrt-18.06.4/master/package/kernel/xradio/Makefile
        
        echo "CONFIG_PACKAGE_kmod-xradio=y" >> .config
        echo "CONFIG_PACKAGE_wireless-regdb=y" >> .config
        
        make defconfig
        echo "Space after configuration:"
        df -h

    - name: Build firmware
      working-directory: openwrt
      run: |
        echo "Starting package downloads..."
        make download -j$(nproc)
        echo "Space after downloads:"
        df -h
        
        echo "Starting build..."
        make -j$(nproc) || (echo "Parallel build failed, cleaning and retrying..." && \
        rm -rf build_dir/target-*/tmp && \
        make -j1 V=sc)
        
        echo "Cleaning up build directory..."
        rm -rf build_dir/target-arm_*/tmp
        rm -rf build_dir/target-arm_*/linux-sunxi_cortexa7/tmp
        
        echo "Final space usage:"
        df -h
        
        echo "Showing ccache statistics:"
        ccache -s

    - name: Organize files
      run: |
        cd openwrt/bin/targets/*
        echo "Build date: $(date '+%Y-%m-%d %H:%M:%S')" > BUILD_INFO.txt
        echo "Built by: ${{ github.actor }}" >> BUILD_INFO.txt
        echo "Commit: ${{ github.sha }}" >> BUILD_INFO.txt
        echo "OpenWrt version: ${OPENWRT_VERSION}" >> BUILD_INFO.txt
        tar czf ../../../OpenWrt-18.06.4-OrangePiZero-H2Plus-xr819.tar.gz *

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-18.06.4-OrangePiZero-H2Plus-xr819-firmware
        path: openwrt/OpenWrt-18.06.4-OrangePiZero-H2Plus-xr819.tar.gz
        retention-days: 90