name: Build OpenWrt for Orange Pi Zero H2+

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      OPENWRT_VERSION: v23.05.2

    steps:
    - name: Initialize Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
        python3-distutils python3-setuptools rsync subversion swig time \
        xsltproc zlib1g-dev 

    # Кэширование
    - name: Cache downloads
      uses: actions/cache@v4
      with:
        path: openwrt/dl
        key: ${{ runner.os }}-openwrt-dl-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-openwrt-dl-

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    # Настройка ccache
    - name: Setup ccache
      run: |
        mkdir -p ~/.ccache
        echo "max_size = 10G" > ~/.ccache/ccache.conf
        echo "hash_dir = false" >> ~/.ccache/ccache.conf

    # Загрузка и распаковка OpenWrt
    - name: Download OpenWrt
      run: |
        wget https://github.com/openwrt/openwrt/archive/refs/tags/${OPENWRT_VERSION}.tar.gz
        tar -xvf ${OPENWRT_VERSION}.tar.gz
        mv openwrt-* openwrt

    # Загрузка и применение патчей
    - name: Download and apply patches
      working-directory: openwrt
      run: |
        wget https://github.com/melsem/opi-zero-cyberwrt/raw/master/patch/All_openwrt-23.05.2.patch
        wget https://github.com/melsem/opi-zero-cyberwrt/raw/master/patch/036-.config_openwrt-23.05.2.patch
        
        ./scripts/feeds update -a
        patch -p1 < All_openwrt-23.05.2.patch
        ./scripts/feeds update opicyberwrt
        ./scripts/feeds update diskman
        ./scripts/feeds install -a
        patch -p1 < 036-.config_openwrt-23.05.2.patch

    # Сборка
    - name: Build firmware
      working-directory: openwrt
      run: |
        make defconfig
        make download -j$(nproc)
        make -j$(nproc) || make -j1 V=s
        echo "::group::CCache statistics"
        ccache -s
        echo "::endgroup::"

    # Сохранение результатов
    - name: Organize files
      run: |
        cd openwrt/bin/targets/*
        echo "Build date: $(date '+%Y-%m-%d %H:%M:%S')" > BUILD_INFO.txt
        tar czf ../../../OpenWrt-OrangePiZero-H2Plus-full.tar.gz *

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-OrangePiZero-H2Plus-firmware
        path: openwrt/OpenWrt-OrangePiZero-H2Plus-full.tar.gz