name: Build XR819 Driver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Setup ImmortalWrt SDK
        run: |
          wget https://downloads.immortalwrt.org/releases/24.10.0-rc3/targets/sunxi/cortexa7/immortalwrt-sdk-24.10.0-rc3-sunxi-cortexa7_gcc-12.3.0_musl_eabi.Linux-x86_64.tar.xz
          tar xf immortalwrt-sdk-*.tar.xz
          cd immortalwrt-sdk-*
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Clone and prepare XR819 driver
        run: |
          git clone https://github.com/fifteenhex/xradio.git package/xr819
          cat > package/xr819/Makefile << 'EOF'
          include $(TOPDIR)/rules.mk
          
          PKG_NAME:=kmod-xr819
          PKG_VERSION:=1.0
          PKG_RELEASE:=1
          
          PKG_BUILD_DIR:=$(KERNEL_BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)
          
          include $(INCLUDE_DIR)/kernel.mk
          include $(INCLUDE_DIR)/package.mk
          
          define KernelPackage/xr819
            SUBMENU:=Wireless Drivers
            TITLE:=XR819 SDIO WIFI support
            DEPENDS:=+kmod-mac80211 +@DRIVER_11N_SUPPORT
            FILES:=$(PKG_BUILD_DIR)/xradio_wlan.ko
            AUTOLOAD:=$(call AutoLoad,50,xradio_wlan)
          endef
          
          define KernelPackage/xr819/description
            Support for XR819 SDIO WiFi module found in OrangePi Zero
          endef
          
          define Build/Prepare
            mkdir -p $(PKG_BUILD_DIR)
            cp -r ./src/* $(PKG_BUILD_DIR)/
          endef
          
          MAKE_OPTS:= \
            ARCH="$(LINUX_KARCH)" \
            CROSS_COMPILE="$(TARGET_CROSS)" \
            SUBDIRS="$(PKG_BUILD_DIR)" \
            KERNELDIR="$(LINUX_DIR)"
          
          define Build/Compile
            $(MAKE) -C "$(LINUX_DIR)" \
              $(MAKE_OPTS) \
              modules
          endef
          
          $(eval $(call KernelPackage,xr819))
          EOF

      - name: Configure and build
        run: |
          cd immortalwrt-sdk-*
          echo 'CONFIG_PACKAGE_kmod-xr819=y' >> .config
          make defconfig
          make package/xr819/compile V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xr819-driver
          path: immortalwrt-sdk-*/bin/packages/*/base/kmod-xr819_*.ipk
